 GET http://localhost:3000/temples/


### Get user contact by ID
GET http://localhost:3000/temples/61a921f6028954d4f0319e90

### Create user contact
POST  http://localhost:3000/temples/ HTTP/1.1
Content-Type: application/json

{
  "_id": {
    "$oid": "69725d539080de00fefd2161"
  },
    "temple_id": "req.body.temple_id",
		"additionalInfo": "req.body.additionalInfo",
		"name":" req.body.name",
		"location": "req.body.location",
		"dedicated": "req.body.dedicated"
}

### Update user contact by ID
PUT http://localhost:3000/temples/69725d539080de00fefd2161
Content-Type: application/json

{
  "temple_id": "req.body.temple_id",
		"additionalInfo": "req.body.additionalInfo",
		"name":" req.body.name",
		"location": "req.body.location",
		"dedicated": "req.body.dedicated"
}